version: 2.1
defaults: &defaults
  resource_class: large
  working_directory: ~/capacity-api
  docker:
    - image: draytechnologies/circleci-python-postgis:3.6.8
    - image: mdillon/postgis:9.6
    - image: rabbitmq:3.5.4
    - image: bitnami/elasticsearch:6.8.12

jobs:
  build:
    <<: *defaults
    steps:
      # Steps to build

  deploy-staging:
    <<: *defaults
    steps:
      # Steps to staging deploy

  deploy-production:
    <<: *defaults
    steps:
      # Steps to deploy to production

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - deploy-staging:
      # Deploy to production whenever there is a new commit on staging branch
          filters:
            branches:
              only:
                - staging
          requires:
            - build
      - deploy-production:
      # Deploy to production when tag in vX.X.X form is pushed
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
            - build

